# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: sgssbangalore
#   labels:
#     app: sgssbangalore
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sgssbangalore
#   template:
#     metadata:
#       labels:
#         app: sgssbangalore
#     spec:
#       containers:
#         - name: sgssbangalore
#           image: gcr.io/GOOGLE_CLOUD_PROJECT/sgssbangalore-cloudbuild:COMMIT_SHA
#           ports:
#             - containerPort: 8095
#               protocol: TCP
# ---
kind: Service
apiVersion: v1
metadata:
  name: sgssbangalore
  labels:
    app: sgssbangalore
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8095
  selector:
    app: sgssbangalore
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: sgssbangalore-ingress
spec:
  tls:
    - hosts:
      - gurdwara.helojobs.in
      - gurdwara.liquidco.in
      secretName: secret-liquidco-20220714
  ingressClassName: nginx
  rules:
    - host: gurdwara.helojobs.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sgssbangalore
                port:
                  number: 80
    - host: gurdwara.liquidco.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sgssbangalore
                port:
                  number: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: sgssbangalore-ingress-sg
spec:
  tls:
    - hosts:
      - gurdwara.supergroup.ai
      secretName: secret-supergroup-20221220
  ingressClassName: nginx
  rules:
    - host: gurdwara.supergroup.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sgssbangalore
                port:
                  number: 80
